[accounts.gmail]
default = true
email = "minhquan010710@gmail.com"
display-name = "Minh Quan"

backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.encryption.type = "tls"
backend.login = "minhquan010710@gmail.com"
backend.auth.type = "password"
backend.auth.cmd = "printenv GMAIL_APP_PASSWORD"

message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 465
message.send.backend.encryption.type = "tls"
message.send.backend.login = "minhquan010710@gmail.com"
message.send.backend.auth.type = "password"
message.send.backend.auth.cmd = "printenv GMAIL_APP_PASSWORD"
