hide_header         = false
compact_mode        = false
default_namespace   = "default"  
default_resource    = "pods"
readonly            = false  
mouse               = true
mouse_scroll_lines  = 3
terminal_title      = true
remember_sort       = false 
favorite_namespaces = ["default", "kube-system"]

[skin]
name = "catppuccin-mocha"
background = true

[debug]
image="nicolaka/netshoot:latest"
command=["bash"]
node_image="nicolaka/netshoot:latest"
node_namespace="default"
